//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sandhya_27.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int StdId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Country { get; set; }
        public string states { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
