//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sandhya_27.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentTable
    {
        public int studentId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Gender { get; set; }
        public string Subject { get; set; }
        public string Address { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
